language: python
python:
  - "3.6.2"

#Install dependecies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install PyYAML-3.11-cp35-none-win32.whl
  
#Run tests
script:
  - python -m unittest
  - coverage
  - coveralls

after_success:
  - coveralls
