language: python
python:
  - "3.6.2"

#Install dependecies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install py.test-cov
  - coveralls
  

#Run tests
script:
  - python -m unittest
