language: python
python:
  - "3.6.2"

#Install dependecies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - coverage run --source=mypkg setup.py test
  - coveralls
  

#Run tests
script:
  - python -m unittest
